### PR TITLE
Add alternative display function to README.org

### PR DESCRIPTION
**Pull request by benthamite**
As discussed here: https://www.reddit.com/r/emacs/comments/1fb0vgp/comment/lm78dia/

### CODE REVIEW

**Comment by ISouthRain** [comment]
> As discussed here: https://www.reddit.com/r/emacs/comments/1fb0vgp/comment/lm78dia/

Oh, thank you very much!
Now there are two questions:
1. If it is not "English", it will put the time on the next line, but this is not a big problem, I will accept it, I wonder if you can solve it? Like this:
图片
2. If the frame size is less than the commit length, it will report an error. I hope it can be solved..., like this:
error in process sentinel: concat: Wrong type argument: wholenump, -9
error in process sentinel: Wrong type argument: wholenump, -9
Preview

3. Please unify the display function codes..
```emacs-lisp
;; Your
;; (setq my--emsg-blame-display #'my--emsg-blame-display)
;;  Correct
(setq emsg-blame-display #'my--emsg-blame-display)
```
Then, I will accept your pr, thank you again.

**Comment by benthamite** [comment]
Thanks for reporting these issues.

- 01e0484731ddb38434abf8396feadfa18b6ae448 fixes the second issue.

- 1121970a754e2726bd5ab2477947e9d0e0ffc1ec fixes the third issue.

Unfortunately, I’m not sure how to fix the first issue. Do you have a sense of what may be causing it?

**Comment by ISouthRain** [comment]
> Unfortunately, I’m not sure how to fix the first issue. Do you have a sense of what may be causing it?

Done fix.
https://github.com/ISouthRain/emsg-blame/commit/8f9d5c2d35f45a626b1b5d6bd5a01032ff430e56

**Comment by benthamite** [comment]
Not sure if I can add to a closed PR, but `(message-log-max nil)` should be added to the let-bound variables to prevent the messages displayed in the echo area to be logged to the \*messages\* buffer. Using your revised code:

``` emacs-lisp
(defun my--emsg-blame-display ()
  "Display git blame message, right-aligned with Magit-style faces.
If another message is already being displayed, display both messages unless they
do not both fit in the echo area."
  (let* ((message-log-max nil) ; prevent messages from being logged to *Messages*
         (cur-msg (or (current-message) ""))
		 (blm-msg (format "%s %s %s "
						  emsg-blame--commit-summary
						  (propertize emsg-blame--commit-author 'face 'magit-log-author)
						  (propertize emsg-blame--commit-date 'face 'magit-log-date)))
		 (available-width (max 0 (- (frame-width) (string-width cur-msg) 1)))
		 (blm-msg-width (string-width blm-msg))
		 (padding (max 0 (- available-width blm-msg-width)))
		 (rev-blm-msg (concat (make-string padding ?\s) blm-msg)))
	(if (> blm-msg-width available-width)
		(message blm-msg)
	  (message (concat cur-msg rev-blm-msg)))))
```

Feel free to update the `README.org` file.

**Comment by ISouthRain** [comment]
Thanks you !!
Done.

**Pull request merged**
